language: go

go:
  - '1.13'

env:
  - GOARCH=amd64

install:
  - go get ./...
  - go get -v modernc.org/ql/ql

services:
  - mongodb

# this is too old to be supported, we're only going to test if it compiles.
script:
  - cd $HOME/gopath/src/github.com/upper/db
  - go build github.com/upper/db/postgresql
  - go build github.com/upper/db/mysql
  - go build github.com/upper/db/mongo
  - go build github.com/upper/db/ql
  - go build github.com/upper/db/sqlite
